ALTER TABLE "CollectRecord" ADD COLUMN IF NOT EXISTS "utmId" TEXT;
ALTER TABLE "CollectRecord" ADD COLUMN IF NOT EXISTS "firstUtmId" TEXT;
ALTER TABLE "CollectRecord" ADD COLUMN IF NOT EXISTS "journey" JSONB;
